name: Build-Test

on:
  push:
    branches: [ "*", "!main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build main library
      working-directory: ./
      run: cargo build --verbose --all-features
    - name: Run main library tests
      working-directory: ./
      run: cargo test --verbose --all-features
